// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cron is an autogenerated mock type for the Cron type
type Cron struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *Cron) Start() {
	_m.Called()
}
