// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PQ is an autogenerated mock type for the PQ type
type PQ struct {
	mock.Mock
}

// Len provides a mock function with given fields:
func (_m *PQ) Len() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Pop provides a mock function with given fields:
func (_m *PQ) Pop() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Push provides a mock function with given fields: _a0
func (_m *PQ) Push(_a0 interface{}) {
	_m.Called(_a0)
}
